Assignment3 = Babikov Aleksandr st135743@student.spbu.ru


CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17
TARGET = Assignment3



all: $(TARGET)

$(TARGET): $(SRCS) $(HEADERS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS)

clean:
	rm -f $(TARGET)

